import type { BancoDados, Equipamento, Medicao, OrdemServico, Peca, PlanoManutencao, CodigoFalha } from "./types"
import { diasAFrente, diasAtras } from "./format"

const equipamentos: Equipamento[] = [
  {
    id: "eq-001",
    tag: "SM-USI-01",
    tipo: "servomotor",
    fabricante: "Yaskawa",
    modelo: "SGM7G-13AFC61",
    numeroSerie: "YK7G-2210-4471",
    setor: "Usinagem",
    maquina: "Centro de Usinagem CNC-01",
    eixo: "Eixo X",
    status: "operando",
    criticidade: "alta",
    instaladoEm: diasAtras(920),
    horasOperacao: 14320,
    potenciaKw: 1.3,
    torqueNominalNm: 8.34,
    rotacaoNominalRpm: 1500,
    correnteNominalA: 9.4,
    tipoEncoder: "Absoluto 24 bits",
    freio: true,
    grauProtecao: "IP67",
    observacoes: "Motor acoplado a fuso de esferas com redução 1:2.",
  },
  {
    id: "eq-002",
    tag: "SD-USI-01",
    tipo: "servodrive",
    fabricante: "Yaskawa",
    modelo: "SGD7S-120A00A",
    numeroSerie: "YK7S-2210-8823",
    setor: "Usinagem",
    maquina: "Centro de Usinagem CNC-01",
    eixo: "Eixo X",
    status: "operando",
    criticidade: "alta",
    instaladoEm: diasAtras(920),
    horasOperacao: 14320,
    tensaoV: 220,
    correnteSaidaA: 11.6,
    firmware: "v2.42",
    modoControle: "Torque / Velocidade",
    realimentacao: "Encoder serial absoluto",
  },
  {
    id: "eq-003",
    tag: "SM-USI-02",
    tipo: "servomotor",
    fabricante: "Fanuc",
    modelo: "αiF 22/3000",
    numeroSerie: "FN22-2019-1180",
    setor: "Usinagem",
    maquina: "Torno CNC-04",
    eixo: "Eixo Z",
    status: "em_manutencao",
    criticidade: "alta",
    instaladoEm: diasAtras(1580),
    horasOperacao: 22840,
    potenciaKw: 3.0,
    torqueNominalNm: 22,
    rotacaoNominalRpm: 3000,
    correnteNominalA: 16.5,
    tipoEncoder: "αiA1000",
    freio: true,
    grauProtecao: "IP65",
    observacoes: "Histórico de superaquecimento em regime de desbaste pesado.",
  },
  {
    id: "eq-004",
    tag: "SD-USI-02",
    tipo: "servodrive",
    fabricante: "Fanuc",
    modelo: "αiSV 40/40",
    numeroSerie: "FNSV-2019-3320",
    setor: "Usinagem",
    maquina: "Torno CNC-04",
    eixo: "Eixo Z",
    status: "operando",
    criticidade: "alta",
    instaladoEm: diasAtras(1580),
    horasOperacao: 22840,
    tensaoV: 400,
    correnteSaidaA: 40,
    firmware: "9D53/06",
    modoControle: "Vetorial",
    realimentacao: "Encoder serial + FSSB",
  },
  {
    id: "eq-005",
    tag: "SM-EST-01",
    tipo: "servomotor",
    fabricante: "Siemens",
    modelo: "1FK7063-5AF71-1AG0",
    numeroSerie: "SI1FK-2021-7712",
    setor: "Estamparia",
    maquina: "Prensa Servo PS-200",
    eixo: "Alimentador",
    status: "operando",
    criticidade: "alta",
    instaladoEm: diasAtras(1240),
    horasOperacao: 18960,
    potenciaKw: 2.4,
    torqueNominalNm: 11,
    rotacaoNominalRpm: 3000,
    correnteNominalA: 7.5,
    tipoEncoder: "Absoluto multivoltas 22 bits",
    freio: true,
    grauProtecao: "IP65",
  },
  {
    id: "eq-006",
    tag: "SD-EST-01",
    tipo: "servodrive",
    fabricante: "Siemens",
    modelo: "SINAMICS S120 6SL3120-1TE21-8AC0",
    numeroSerie: "SIS12-2021-9903",
    setor: "Estamparia",
    maquina: "Prensa Servo PS-200",
    eixo: "Alimentador",
    status: "em_manutencao",
    criticidade: "alta",
    instaladoEm: diasAtras(1240),
    horasOperacao: 18960,
    tensaoV: 400,
    correnteSaidaA: 18,
    firmware: "5.2 SP3",
    modoControle: "Servo",
    realimentacao: "DRIVE-CLiQ",
  },
  {
    id: "eq-007",
    tag: "SM-INJ-01",
    tipo: "servomotor",
    fabricante: "Mitsubishi",
    modelo: "HG-SR202B",
    numeroSerie: "MHG-2020-5541",
    setor: "Injeção",
    maquina: "Injetora IJ-12",
    eixo: "Dosagem",
    status: "operando",
    criticidade: "media",
    instaladoEm: diasAtras(1460),
    horasOperacao: 20110,
    potenciaKw: 2.0,
    torqueNominalNm: 9.55,
    rotacaoNominalRpm: 2000,
    correnteNominalA: 11,
    tipoEncoder: "Absoluto 22 bits",
    freio: true,
    grauProtecao: "IP67",
  },
  {
    id: "eq-008",
    tag: "SD-INJ-01",
    tipo: "servodrive",
    fabricante: "Mitsubishi",
    modelo: "MR-J4-200B",
    numeroSerie: "MRJ4-2020-2218",
    setor: "Injeção",
    maquina: "Injetora IJ-12",
    eixo: "Dosagem",
    status: "operando",
    criticidade: "media",
    instaladoEm: diasAtras(1460),
    horasOperacao: 20110,
    tensaoV: 220,
    correnteSaidaA: 11,
    firmware: "B8",
    modoControle: "Posição (SSCNET III/H)",
    realimentacao: "Encoder absoluto",
  },
  {
    id: "eq-009",
    tag: "SM-MON-01",
    tipo: "servomotor",
    fabricante: "Allen-Bradley",
    modelo: "MPL-B430P-MJ72AA",
    numeroSerie: "ABMP-2022-1094",
    setor: "Montagem",
    maquina: "Robô Cartesiano RC-03",
    eixo: "Eixo Y",
    status: "operando",
    criticidade: "media",
    instaladoEm: diasAtras(760),
    horasOperacao: 9840,
    potenciaKw: 1.6,
    torqueNominalNm: 5.7,
    rotacaoNominalRpm: 5000,
    correnteNominalA: 6.7,
    tipoEncoder: "Absoluto multivoltas",
    freio: false,
    grauProtecao: "IP65",
  },
  {
    id: "eq-010",
    tag: "SD-MON-01",
    tipo: "servodrive",
    fabricante: "Allen-Bradley",
    modelo: "Kinetix 5700 2198-D020-ERS3",
    numeroSerie: "K57-2022-6612",
    setor: "Montagem",
    maquina: "Robô Cartesiano RC-03",
    eixo: "Eixo Y",
    status: "operando",
    criticidade: "media",
    instaladoEm: diasAtras(760),
    horasOperacao: 9840,
    tensaoV: 400,
    correnteSaidaA: 20,
    firmware: "13.001",
    modoControle: "CIP Motion",
    realimentacao: "Hiperface DSL",
  },
  {
    id: "eq-011",
    tag: "SM-EMB-01",
    tipo: "servomotor",
    fabricante: "WEG",
    modelo: "SWA-190M-30-1S1",
    numeroSerie: "WG19-2023-3345",
    setor: "Embalagem",
    maquina: "Envasadora EN-07",
    eixo: "Rosca dosadora",
    status: "reserva",
    criticidade: "baixa",
    instaladoEm: diasAtras(430),
    horasOperacao: 4120,
    potenciaKw: 1.9,
    torqueNominalNm: 6.0,
    rotacaoNominalRpm: 3000,
    correnteNominalA: 5.8,
    tipoEncoder: "Absoluto 20 bits",
    freio: false,
    grauProtecao: "IP65",
    observacoes: "Motor reserva estratégico do setor de embalagem.",
  },
  {
    id: "eq-012",
    tag: "SD-EMB-01",
    tipo: "servodrive",
    fabricante: "WEG",
    modelo: "SCA06 0009 T2",
    numeroSerie: "SCA6-2023-8890",
    setor: "Embalagem",
    maquina: "Envasadora EN-07",
    eixo: "Rosca dosadora",
    status: "parado",
    criticidade: "media",
    instaladoEm: diasAtras(430),
    horasOperacao: 4120,
    tensaoV: 220,
    correnteSaidaA: 9,
    firmware: "1.70",
    modoControle: "Posicionamento",
    realimentacao: "Encoder incremental + resolver",
  },
]

const pecas: Peca[] = [
  { id: "pc-001", codigo: "ENC-YK-24B", descricao: "Encoder absoluto serial 24 bits Sigma-7", categoria: "encoder", fabricante: "Yaskawa", aplicacao: "SGM7G / SGM7J", estoque: 2, estoqueMinimo: 1, custoUnitario: 4850, localizacao: "Almox. A-12", fornecedor: "Yaskawa do Brasil" },
  { id: "pc-002", codigo: "ROL-6205-2RS", descricao: "Rolamento rígido de esferas 6205-2RS C3", categoria: "rolamento", fabricante: "SKF", aplicacao: "Servomotores 1,0 a 3,0 kW", estoque: 8, estoqueMinimo: 6, custoUnitario: 92, localizacao: "Almox. B-03", fornecedor: "Rolamentos Industriais SA" },
  { id: "pc-003", codigo: "ROL-6003-2RS", descricao: "Rolamento traseiro 6003-2RS", categoria: "rolamento", fabricante: "NSK", aplicacao: "Servomotores até 2,0 kW", estoque: 3, estoqueMinimo: 6, custoUnitario: 68, localizacao: "Almox. B-03", fornecedor: "Rolamentos Industriais SA" },
  { id: "pc-004", codigo: "VENT-24V-80", descricao: "Ventoinha axial 80x80 mm 24 Vcc", categoria: "ventoinha", fabricante: "Sunon", aplicacao: "Servodrives 200/400 V", estoque: 5, estoqueMinimo: 4, custoUnitario: 145, localizacao: "Almox. A-07", fornecedor: "Componel" },
  { id: "pc-005", codigo: "IGBT-6MBI50", descricao: "Módulo IGBT 6MBI50VA-120-50", categoria: "modulo_potencia", fabricante: "Fuji", aplicacao: "Servodrives 400 V até 20 A", estoque: 1, estoqueMinimo: 2, custoUnitario: 2380, localizacao: "Almox. A-01", fornecedor: "Eletrônica Industrial LTDA" },
  { id: "pc-006", codigo: "BAT-ER6V", descricao: "Bateria de encoder absoluto 3,6 V ER6V", categoria: "bateria", fabricante: "Toshiba", aplicacao: "Encoders absolutos multivoltas", estoque: 12, estoqueMinimo: 8, custoUnitario: 78, localizacao: "Almox. C-05", fornecedor: "Componel" },
  { id: "pc-007", codigo: "CAB-DQ-5M", descricao: "Cabo DRIVE-CLiQ blindado 5 m", categoria: "cabo", fabricante: "Siemens", aplicacao: "SINAMICS S120", estoque: 2, estoqueMinimo: 2, custoUnitario: 960, localizacao: "Almox. A-15", fornecedor: "Siemens Brasil" },
  { id: "pc-008", codigo: "CAB-PWR-4X2.5", descricao: "Cabo de potência blindado 4x2,5 mm² para servo", categoria: "cabo", fabricante: "Lapp", aplicacao: "Servomotores 1,5 a 3,0 kW", estoque: 40, estoqueMinimo: 20, custoUnitario: 62, localizacao: "Almox. D-02", fornecedor: "Lapp Brasil" },
  { id: "pc-009", codigo: "PLC-CTRL-MRJ4", descricao: "Placa de controle MR-J4-200B", categoria: "placa_eletronica", fabricante: "Mitsubishi", aplicacao: "MR-J4-200B", estoque: 0, estoqueMinimo: 1, custoUnitario: 5200, localizacao: "Almox. A-02", fornecedor: "Mitsubishi Electric" },
  { id: "pc-010", codigo: "FRE-24V-10NM", descricao: "Freio eletromagnético 24 Vcc 10 Nm", categoria: "freio", fabricante: "Kendrion", aplicacao: "Servomotores com freio", estoque: 2, estoqueMinimo: 1, custoUnitario: 1290, localizacao: "Almox. B-10", fornecedor: "Kendrion do Brasil" },
  { id: "pc-011", codigo: "RET-VS-35", descricao: "Retentor de eixo VS 35x47x7", categoria: "vedacao", fabricante: "Sabo", aplicacao: "Servomotores flange 130 mm", estoque: 6, estoqueMinimo: 4, custoUnitario: 34, localizacao: "Almox. B-06", fornecedor: "Sabo" },
  { id: "pc-012", codigo: "CAP-BUS-470", descricao: "Capacitor de barramento 470 µF 450 V", categoria: "modulo_potencia", fabricante: "Epcos", aplicacao: "Servodrives 400 V", estoque: 4, estoqueMinimo: 4, custoUnitario: 310, localizacao: "Almox. A-04", fornecedor: "Eletrônica Industrial LTDA" },
]

const falhas: CodigoFalha[] = [
  {
    id: "fl-001", codigo: "A.C90", fabricante: "Yaskawa", linha: "Sigma-7 / Sigma-5", severidade: "critica",
    descricao: "Erro de comunicação com o encoder do servomotor.",
    causasProvaveis: ["Cabo de encoder rompido, prensado ou com malha aberta", "Conector do encoder mal fixado ou oxidado", "Ruído eletromagnético por aterramento deficiente", "Encoder danificado por sobretemperatura"],
    acoesRecomendadas: ["Inspecionar e testar continuidade do cabo de encoder", "Refazer conectorização e verificar torque de fixação", "Conferir aterramento da malha em ponto único no drive", "Substituir o encoder se o erro persistir com cabo novo"],
  },
  {
    id: "fl-002", codigo: "A.710", fabricante: "Yaskawa", linha: "Sigma-7", severidade: "alta",
    descricao: "Sobrecarga instantânea (alta carga) no servomotor.",
    causasProvaveis: ["Travamento mecânico do eixo ou guia", "Lubrificação deficiente do fuso", "Dimensionamento incorreto para o ciclo", "Freio não liberando totalmente"],
    acoesRecomendadas: ["Verificar torque de giro manual do conjunto", "Lubrificar guias e fusos conforme plano", "Analisar curva de torque x tempo do ciclo", "Medir tensão de acionamento do freio (24 Vcc)"],
  },
  {
    id: "fl-003", codigo: "A.810", fabricante: "Yaskawa", linha: "Sigma-7", severidade: "media",
    descricao: "Alarme de backup do encoder absoluto (perda de referência).",
    causasProvaveis: ["Bateria do encoder descarregada", "Cabo de encoder desconectado com drive desenergizado", "Falha do circuito de retenção do encoder"],
    acoesRecomendadas: ["Substituir a bateria do encoder", "Executar reset de encoder absoluto e refazer referenciamento", "Registrar a nova origem da máquina"],
  },
  {
    id: "fl-004", codigo: "F30001", fabricante: "Siemens", linha: "SINAMICS S120", severidade: "critica",
    descricao: "Sobrecorrente no estágio de potência.",
    causasProvaveis: ["Curto entre fases no cabo do motor", "Enrolamento do motor em curto ou com isolação degradada", "Rampa de aceleração muito agressiva", "Módulo IGBT danificado"],
    acoesRecomendadas: ["Medir resistência de isolamento do motor (megômetro 500 V)", "Testar cabo de potência fase-fase e fase-terra", "Revisar rampas e limites de corrente nos parâmetros", "Substituir o módulo de potência se necessário"],
  },
  {
    id: "fl-005", codigo: "F30004", fabricante: "Siemens", linha: "SINAMICS S120", severidade: "alta",
    descricao: "Sobretemperatura do dissipador do inversor.",
    causasProvaveis: ["Ventoinha travada ou com rotação reduzida", "Filtro do painel saturado", "Temperatura ambiente acima do projeto", "Dissipador com acúmulo de pó"],
    acoesRecomendadas: ["Substituir ventoinha e limpar dissipador", "Trocar filtros e verificar climatização do painel", "Registrar temperatura interna do painel no plano preditivo"],
  },
  {
    id: "fl-006", codigo: "F31117", fabricante: "Siemens", linha: "SINAMICS S120", severidade: "alta",
    descricao: "Falha no canal de realimentação DRIVE-CLiQ do encoder.",
    causasProvaveis: ["Cabo DRIVE-CLiQ danificado", "Sensor Module com defeito", "Interferência eletromagnética no trajeto do cabo"],
    acoesRecomendadas: ["Substituir cabo DRIVE-CLiQ por unidade nova", "Separar cabos de sinal e de potência na canaleta", "Substituir Sensor Module se o erro persistir"],
  },
  {
    id: "fl-007", codigo: "SV0430", fabricante: "Fanuc", linha: "αi Servo", severidade: "critica",
    descricao: "Sobreaquecimento do servomotor (termostato atuado).",
    causasProvaveis: ["Ciclo de trabalho acima do nominal", "Ventilação obstruída na carcaça", "Atrito excessivo por guia desalinhada", "Termostato ou cabo de sinal com falha"],
    acoesRecomendadas: ["Medir corrente eficaz durante o ciclo", "Limpar carcaça e verificar refrigeração", "Alinhar acoplamento e conferir pré-carga das guias", "Testar continuidade do termostato"],
  },
  {
    id: "fl-008", codigo: "SV0601", fabricante: "Fanuc", linha: "αi Servo", severidade: "media",
    descricao: "Falha do ventilador interno do amplificador servo.",
    causasProvaveis: ["Rolamento da ventoinha desgastado", "Cabo de alimentação da ventoinha rompido", "Acúmulo de sujeira travando o rotor"],
    acoesRecomendadas: ["Substituir a ventoinha do amplificador", "Limpar interior do painel", "Incluir troca preventiva a cada 20.000 h"],
  },
  {
    id: "fl-009", codigo: "AL.16", fabricante: "Mitsubishi", linha: "MR-J4", severidade: "critica",
    descricao: "Erro de encoder (comunicação inicial).",
    causasProvaveis: ["Cabo do encoder com mau contato", "Encoder com umidade ou contaminação", "Placa de controle do drive com defeito"],
    acoesRecomendadas: ["Reconectorizar e testar o cabo do encoder", "Secar e inspecionar o encoder", "Substituir a placa de controle do drive"],
  },
  {
    id: "fl-010", codigo: "AL.33", fabricante: "Mitsubishi", linha: "MR-J4", severidade: "alta",
    descricao: "Sobretensão no barramento CC.",
    causasProvaveis: ["Resistor de frenagem subdimensionado ou aberto", "Desaceleração muito rápida com alta inércia", "Tensão de rede acima do limite"],
    acoesRecomendadas: ["Medir resistência do resistor de frenagem", "Ajustar rampa de desaceleração", "Verificar tensão de alimentação e transformador"],
  },
  {
    id: "fl-011", codigo: "AL.50", fabricante: "Mitsubishi", linha: "MR-J4", severidade: "alta",
    descricao: "Sobrecarga 1 (proteção térmica por I²t).",
    causasProvaveis: ["Carga mecânica acima do previsto", "Ganho do laço de posição mal ajustado gerando oscilação", "Freio parcialmente aplicado"],
    acoesRecomendadas: ["Executar auto-tuning do drive", "Verificar liberação do freio e folga do acoplamento", "Reavaliar dimensionamento do servo para o ciclo"],
  },
  {
    id: "fl-012", codigo: "E19", fabricante: "Allen-Bradley", linha: "Kinetix 5700", severidade: "critica",
    descricao: "Sobrecorrente de saída do eixo.",
    causasProvaveis: ["Curto no cabo de potência do motor", "Motor com isolação comprometida", "Parâmetros de malha de corrente incorretos"],
    acoesRecomendadas: ["Isolar o cabo e testar o motor separadamente", "Medir isolação dos enrolamentos", "Restaurar backup de parâmetros validado"],
  },
  {
    id: "fl-013", codigo: "E09", fabricante: "Allen-Bradley", linha: "Kinetix 5700", severidade: "alta",
    descricao: "Sobretensão no barramento CC.",
    causasProvaveis: ["Energia regenerativa acima da capacidade do módulo", "Resistor shunt desconectado", "Rede com surtos de tensão"],
    acoesRecomendadas: ["Dimensionar/instalar resistor shunt adequado", "Verificar conexões do módulo de frenagem", "Monitorar qualidade de energia da linha"],
  },
  {
    id: "fl-014", codigo: "F0021", fabricante: "WEG", linha: "SCA06", severidade: "alta",
    descricao: "Falha de realimentação de posição (encoder/resolver).",
    causasProvaveis: ["Resolver desalinhado após montagem", "Cabo de sinal com blindagem aberta", "Parâmetro de número de pulsos incorreto"],
    acoesRecomendadas: ["Refazer o alinhamento do resolver", "Conferir blindagem aterrada apenas no drive", "Validar parametrização de realimentação"],
  },
]

function os(o: OrdemServico): OrdemServico {
  return o
}

const ordens: OrdemServico[] = [
  os({
    id: "os-001", codigo: "OS-2026-0001", equipamentoId: "eq-003", tipo: "corretiva", status: "em_execucao", prioridade: "critica",
    titulo: "Superaquecimento do servomotor do eixo Z", sintoma: "Alarme SV0430 após 40 min de usinagem em desbaste. Carcaça acima de 85 °C.",
    codigoAlarme: "SV0430", diagnostico: "Ventilação obstruída e rolamento traseiro com ruído. Corrente eficaz 18% acima do histórico.",
    causaRaiz: "Desgaste de rolamento gerando atrito e elevação térmica.",
    acoesExecutadas: "Desmontagem do motor, limpeza da carcaça e substituição do rolamento traseiro em andamento.",
    tecnico: "Marcos Vieira", abertaEm: diasAtras(3), iniciadaEm: diasAtras(2),
    horasParada: 11, horasMaoDeObra: 8, custoPecas: 136, custoServicoExterno: 0,
    pecas: [{ pecaId: "pc-003", quantidade: 2 }],
  }),
  os({
    id: "os-002", codigo: "OS-2026-0002", equipamentoId: "eq-006", tipo: "corretiva", status: "aguardando_peca", prioridade: "alta",
    titulo: "Falha de realimentação DRIVE-CLiQ", sintoma: "Drive apresenta F31117 de forma intermitente durante o ciclo da prensa.",
    codigoAlarme: "F31117", diagnostico: "Cabo DRIVE-CLiQ com malha rompida próximo ao conector do motor.",
    tecnico: "Ana Paula Reis", abertaEm: diasAtras(6), iniciadaEm: diasAtras(5),
    horasParada: 26, horasMaoDeObra: 5, custoPecas: 960, custoServicoExterno: 0,
    pecas: [{ pecaId: "pc-007", quantidade: 1 }],
  }),
  os({
    id: "os-003", codigo: "OS-2026-0003", equipamentoId: "eq-012", tipo: "corretiva", status: "aberta", prioridade: "alta",
    titulo: "Servodrive da envasadora não liga", sintoma: "Sem display e sem tensão no barramento CC após queda de energia.",
    codigoAlarme: "F0021", tecnico: "Rafael Nunes", abertaEm: diasAtras(1),
    horasParada: 9, horasMaoDeObra: 0, custoPecas: 0, custoServicoExterno: 0, pecas: [],
  }),
  os({
    id: "os-004", codigo: "OS-2026-0004", equipamentoId: "eq-001", tipo: "preventiva", status: "planejada", prioridade: "media",
    titulo: "Preventiva semestral do servomotor SM-USI-01", sintoma: "Rotina programada conforme plano PL-001.",
    tecnico: "Marcos Vieira", abertaEm: diasAtras(2), programadaPara: diasAFrente(5),
    horasParada: 0, horasMaoDeObra: 0, custoPecas: 0, custoServicoExterno: 0, pecas: [], planoId: "pl-001",
  }),
  os({
    id: "os-005", codigo: "OS-2026-0005", equipamentoId: "eq-008", tipo: "preditiva", status: "planejada", prioridade: "baixa",
    titulo: "Termografia e análise de vibração da injetora IJ-12", sintoma: "Rota preditiva mensal.",
    tecnico: "Ana Paula Reis", abertaEm: diasAtras(4), programadaPara: diasAFrente(9),
    horasParada: 0, horasMaoDeObra: 0, custoPecas: 0, custoServicoExterno: 0, pecas: [], planoId: "pl-004",
  }),
  os({
    id: "os-006", codigo: "OS-2025-0148", equipamentoId: "eq-002", tipo: "corretiva", status: "concluida", prioridade: "critica",
    titulo: "Erro de comunicação com encoder", sintoma: "Drive acusa A.C90 ao energizar a máquina.",
    codigoAlarme: "A.C90", diagnostico: "Cabo de encoder prensado na esteira porta-cabos.",
    causaRaiz: "Raio de curvatura do cabo abaixo do especificado na instalação.",
    acoesExecutadas: "Substituição do cabo de encoder, refeita a fixação na esteira e teste de 8 h em produção.",
    tecnico: "Rafael Nunes", abertaEm: diasAtras(38), iniciadaEm: diasAtras(38), concluidaEm: diasAtras(37),
    horasParada: 6.5, horasMaoDeObra: 5, custoPecas: 620, custoServicoExterno: 0,
    pecas: [{ pecaId: "pc-008", quantidade: 10 }],
  }),
  os({
    id: "os-007", codigo: "OS-2025-0151", equipamentoId: "eq-005", tipo: "preventiva", status: "concluida", prioridade: "media",
    titulo: "Preventiva semestral prensa servo", sintoma: "Rotina programada conforme plano PL-003.",
    acoesExecutadas: "Reaperto de conexões de potência, medição de isolação (>500 MΩ), limpeza e troca de filtros do painel.",
    tecnico: "Marcos Vieira", abertaEm: diasAtras(56), iniciadaEm: diasAtras(55), concluidaEm: diasAtras(55),
    horasParada: 3, horasMaoDeObra: 4, custoPecas: 0, custoServicoExterno: 0, pecas: [], planoId: "pl-003",
  }),
  os({
    id: "os-008", codigo: "OS-2025-0155", equipamentoId: "eq-007", tipo: "corretiva", status: "concluida", prioridade: "alta",
    titulo: "Perda de referência do encoder absoluto", sintoma: "Alarme de bateria e perda de origem após parada de fim de semana.",
    codigoAlarme: "A.810", diagnostico: "Bateria do encoder abaixo de 2,8 V.",
    causaRaiz: "Bateria além da vida útil (não substituída na preventiva anterior).",
    acoesExecutadas: "Troca da bateria, reset do encoder absoluto e novo referenciamento da máquina.",
    tecnico: "Ana Paula Reis", abertaEm: diasAtras(74), iniciadaEm: diasAtras(74), concluidaEm: diasAtras(74),
    horasParada: 2.5, horasMaoDeObra: 2, custoPecas: 78, custoServicoExterno: 0,
    pecas: [{ pecaId: "pc-006", quantidade: 1 }],
  }),
  os({
    id: "os-009", codigo: "OS-2025-0160", equipamentoId: "eq-004", tipo: "corretiva", status: "concluida", prioridade: "alta",
    titulo: "Falha da ventoinha do amplificador", sintoma: "Alarme SV0601 e temperatura elevada no painel.",
    codigoAlarme: "SV0601", diagnostico: "Ventoinha travada por acúmulo de cavaco fino.",
    causaRaiz: "Filtro do painel saturado permitindo entrada de particulado.",
    acoesExecutadas: "Substituição da ventoinha, limpeza do dissipador e troca dos filtros do painel.",
    tecnico: "Rafael Nunes", abertaEm: diasAtras(96), iniciadaEm: diasAtras(96), concluidaEm: diasAtras(95),
    horasParada: 4, horasMaoDeObra: 3, custoPecas: 145, custoServicoExterno: 0,
    pecas: [{ pecaId: "pc-004", quantidade: 1 }],
  }),
  os({
    id: "os-010", codigo: "OS-2025-0166", equipamentoId: "eq-010", tipo: "preventiva", status: "concluida", prioridade: "baixa",
    titulo: "Preventiva anual do servodrive Kinetix", sintoma: "Rotina programada conforme plano PL-005.",
    acoesExecutadas: "Backup de parâmetros, limpeza interna, reaperto de bornes e teste de STO.",
    tecnico: "Marcos Vieira", abertaEm: diasAtras(120), iniciadaEm: diasAtras(119), concluidaEm: diasAtras(119),
    horasParada: 2, horasMaoDeObra: 3, custoPecas: 0, custoServicoExterno: 0, pecas: [], planoId: "pl-005",
  }),
  os({
    id: "os-011", codigo: "OS-2025-0170", equipamentoId: "eq-009", tipo: "corretiva", status: "concluida", prioridade: "media",
    titulo: "Oscilação de posicionamento no eixo Y", sintoma: "Robô apresenta trepidação em baixa velocidade e erro de seguimento.",
    diagnostico: "Ganhos do laço de posição desajustados após troca de garra (mudança de inércia).",
    causaRaiz: "Alteração de carga sem novo auto-tuning.",
    acoesExecutadas: "Auto-tuning do drive, ajuste de filtro de ressonância e validação com 200 ciclos.",
    tecnico: "Ana Paula Reis", abertaEm: diasAtras(142), iniciadaEm: diasAtras(142), concluidaEm: diasAtras(141),
    horasParada: 5, horasMaoDeObra: 6, custoPecas: 0, custoServicoExterno: 0, pecas: [],
  }),
  os({
    id: "os-012", codigo: "OS-2025-0175", equipamentoId: "eq-008", tipo: "corretiva", status: "concluida", prioridade: "critica",
    titulo: "Sobretensão no barramento CC", sintoma: "Drive desarma com AL.33 na desaceleração da dosagem.",
    codigoAlarme: "AL.33", diagnostico: "Resistor de frenagem com elemento aberto.",
    causaRaiz: "Resistor subdimensionado para o novo tempo de ciclo.",
    acoesExecutadas: "Substituição do resistor por modelo de maior potência e revisão da rampa de desaceleração.",
    tecnico: "Rafael Nunes", abertaEm: diasAtras(168), iniciadaEm: diasAtras(168), concluidaEm: diasAtras(167),
    horasParada: 7, horasMaoDeObra: 6, custoPecas: 0, custoServicoExterno: 1850, pecas: [],
  }),
  os({
    id: "os-013", codigo: "OS-2025-0181", equipamentoId: "eq-001", tipo: "preventiva", status: "concluida", prioridade: "media",
    titulo: "Preventiva semestral do servomotor SM-USI-01", sintoma: "Rotina programada conforme plano PL-001.",
    acoesExecutadas: "Medição de isolação, análise de vibração, lubrificação do fuso e reaperto do acoplamento.",
    tecnico: "Marcos Vieira", abertaEm: diasAtras(178), iniciadaEm: diasAtras(177), concluidaEm: diasAtras(177),
    horasParada: 3, horasMaoDeObra: 4, custoPecas: 0, custoServicoExterno: 0, pecas: [], planoId: "pl-001",
  }),
  os({
    id: "os-014", codigo: "OS-2025-0188", equipamentoId: "eq-011", tipo: "calibracao", status: "concluida", prioridade: "baixa",
    titulo: "Calibração e teste do motor reserva", sintoma: "Verificação periódica do sobressalente estratégico.",
    acoesExecutadas: "Teste de giro livre, medição de isolação e recarga da bateria de encoder.",
    tecnico: "Ana Paula Reis", abertaEm: diasAtras(205), iniciadaEm: diasAtras(205), concluidaEm: diasAtras(205),
    horasParada: 0, horasMaoDeObra: 2, custoPecas: 0, custoServicoExterno: 0, pecas: [],
  }),
]

const planos: PlanoManutencao[] = [
  {
    id: "pl-001", nome: "Preventiva semestral - Servomotor CNC-01", equipamentoId: "eq-001", tipo: "preventiva",
    intervaloDias: 180, intervaloHoras: 4000, ultimaExecucao: diasAtras(177), horasNaUltimaExecucao: 12500,
    duracaoEstimadaH: 4, responsavel: "Marcos Vieira", ativo: true,
    checklist: ["Medir resistência de isolamento dos enrolamentos (500 V)", "Analisar vibração nos mancais dianteiro e traseiro", "Verificar folga e alinhamento do acoplamento", "Testar acionamento e liberação do freio", "Inspecionar cabos de potência e encoder", "Lubrificar guias e fuso conforme especificação"],
  },
  {
    id: "pl-002", nome: "Preventiva anual - Servodrive CNC-01", equipamentoId: "eq-002", tipo: "preventiva",
    intervaloDias: 365, ultimaExecucao: diasAtras(300), duracaoEstimadaH: 3, responsavel: "Rafael Nunes", ativo: true,
    checklist: ["Backup dos parâmetros do drive", "Limpeza do dissipador e troca de filtros do painel", "Reaperto dos bornes de potência", "Medir tensão do barramento CC", "Testar função STO", "Registrar versão de firmware"],
  },
  {
    id: "pl-003", nome: "Preventiva semestral - Prensa Servo PS-200", equipamentoId: "eq-005", tipo: "preventiva",
    intervaloDias: 180, intervaloHoras: 3500, ultimaExecucao: diasAtras(55), horasNaUltimaExecucao: 17800,
    duracaoEstimadaH: 4, responsavel: "Marcos Vieira", ativo: true,
    checklist: ["Reaperto das conexões de potência", "Medição de isolação do motor", "Inspeção do sistema de refrigeração do painel", "Verificação do freio de segurança", "Teste de emergência e STO"],
  },
  {
    id: "pl-004", nome: "Rota preditiva mensal - Injeção", equipamentoId: "eq-007", tipo: "preditiva",
    intervaloDias: 30, ultimaExecucao: diasAtras(28), duracaoEstimadaH: 2, responsavel: "Ana Paula Reis", ativo: true,
    checklist: ["Termografia do motor e do painel do drive", "Medição de vibração global (mm/s RMS)", "Registro de corrente eficaz em regime", "Comparação com linha de base histórica"],
  },
  {
    id: "pl-005", nome: "Preventiva anual - Kinetix 5700", equipamentoId: "eq-010", tipo: "preventiva",
    intervaloDias: 365, ultimaExecucao: diasAtras(119), duracaoEstimadaH: 3, responsavel: "Marcos Vieira", ativo: true,
    checklist: ["Backup de parâmetros CIP Motion", "Limpeza interna e das ventoinhas", "Reaperto de bornes", "Verificação do cabo Hiperface DSL", "Teste de STO"],
  },
  {
    id: "pl-006", nome: "Troca de bateria de encoder - Injetora IJ-12", equipamentoId: "eq-008", tipo: "preventiva",
    intervaloDias: 540, ultimaExecucao: diasAtras(530), duracaoEstimadaH: 1, responsavel: "Ana Paula Reis", ativo: true,
    checklist: ["Substituir bateria do encoder absoluto com drive energizado", "Verificar retenção de posição", "Registrar data da troca na etiqueta do drive"],
  },
  {
    id: "pl-007", nome: "Calibração anual do motor reserva", equipamentoId: "eq-011", tipo: "calibracao",
    intervaloDias: 365, ultimaExecucao: diasAtras(205), duracaoEstimadaH: 2, responsavel: "Ana Paula Reis", ativo: true,
    checklist: ["Teste de giro livre", "Medição de isolação", "Verificação da bateria de encoder", "Rotação do estoque de sobressalentes"],
  },
]

function medicoesSeed(): Medicao[] {
  const base: Array<[string, Medicao["tipo"], string, number, number[]]> = [
    ["eq-001", "temperatura", "°C", 80, [58, 61, 60, 63, 62, 64]],
    ["eq-001", "vibracao", "mm/s", 4.5, [1.8, 1.9, 2.1, 2.0, 2.3, 2.4]],
    ["eq-003", "temperatura", "°C", 80, [68, 71, 74, 78, 83, 88]],
    ["eq-003", "vibracao", "mm/s", 4.5, [2.6, 3.0, 3.4, 3.9, 4.4, 5.1]],
    ["eq-005", "temperatura", "°C", 80, [55, 57, 56, 58, 57, 59]],
    ["eq-007", "corrente", "A", 11, [8.2, 8.4, 8.3, 8.8, 9.1, 9.0]],
    ["eq-009", "vibracao", "mm/s", 4.5, [1.2, 1.3, 1.2, 1.4, 1.3, 1.5]],
  ]
  const resultado: Medicao[] = []
  base.forEach(([equipamentoId, tipo, unidade, limite, valores]) => {
    valores.forEach((valor, i) => {
      resultado.push({
        id: `md-${equipamentoId}-${tipo}-${i}`,
        equipamentoId,
        tipo,
        valor,
        unidade,
        limite,
        data: diasAtras((valores.length - 1 - i) * 30 + 2),
        responsavel: "Ana Paula Reis",
      })
    })
  })
  return resultado
}

export function dadosIniciais(): BancoDados {
  return {
    equipamentos,
    ordens,
    planos,
    pecas,
    falhas,
    medicoes: medicoesSeed(),
  }
}
